### ISSUE TITLE
String parsing error

### ISSUE THREAD

**Issue by saanuregh** [jessety/env-smart#1]
When encountering string with equal signs, it fails to parse the string completely

.env
`DB_URL=mongodb+srv://trubot:<password>@trubot-db-eannl.mongodb.net/test?retryWrites=true&w=majority`

is parsed as:
`mongodb+srv://trubot:trubot@trubot-db-eannl.mongodb.net/test?retryWrites`

**Comment by jessety** [comment]
Wow, that's a pretty gnarly bug. Thanks so much for pointing this out!

I just published version `2.0.0` which fixes this.
